#!/bin/python3

# Copyright (c) 2016-2017 Vittorio Romeo
# License: MIT License
# MIT License page: https://opensource.org/licenses/MIT
# http://vittorioromeo.info | vittorio.romeo@outlook.com

import os, stat, sys
import re
import time
import argparse
import json
import pprint
import tempfile

pp = pprint.PrettyPrinter(indent=4)



#
#
#
# -----------------------------------------------------------------------------------------------------------
# Configuration keys
# -----------------------------------------------------------------------------------------------------------

akEnableTemplateCollapsing = 'template-collapsing'
akEnableNamespaceReplacements = 'namespace-replacements'
akEnableGenericReplacements = 'generic-replacements'
akEnableTempCache = 'temp-cache'
akReprocess = 'reprocess'
akReprocessPrevConfig = 'reprocess-prev-config'

ckEnableTemplateCollapsing = 'enableTemplateCollapsing'
ckEnableNamespaceReplacements = 'enableNamespaceReplacements'
ckEnableGenericReplacements = 'enableGenericReplacements'
ckEnableTempCache = 'enableTempCache'
ckTemplateCollapsingDepth = 'templateCollapsingDepth'
ckConfigPaths = 'configPaths'
ckNamespaceReplacements = 'namespaceReplacements'
ckGenericReplacements = 'genericReplacements'
ckCompilationCommand = 'compilationCommand'
ckReprocess = 'reprocess'
ckReprocessPrevConfig = 'reprocessPrevConfig'



#
#
#
# -----------------------------------------------------------------------------------------------------------
# Cache
# -----------------------------------------------------------------------------------------------------------

fkCacheConfigFilePath = tempfile.gettempdir() + "/lastCamomillaConfig.json"
fkCacheFilePath = tempfile.gettempdir() + "/lastCamomilla.out"

def writeTempConfigCache(contents):
    with open(fkCacheConfigFilePath, "w+") as f:
        f.write(contents)

def readTempConfigCache():
    with open(fkCacheConfigFilePath) as f:
        return f.read()

def writeTempCache(contents):
    with open(fkCacheFilePath, "w+") as f:
        f.write(contents)

def readTempCache():
    with open(fkCacheFilePath) as f:
        return f.read()



#
#
#
# -----------------------------------------------------------------------------------------------------------
# Configuration/arg parsing
# -----------------------------------------------------------------------------------------------------------

def addFeatureOpt(ap, flagName, key, defaultValue, helpStr):
    ap_feature = ap.add_mutually_exclusive_group(required=False)
    ap_feature.add_argument('--' + flagName, dest=key, action='store_true', help="| Control " + helpStr)
    ap_feature.add_argument('--no-' + flagName, dest=key, action='store_false', help="'")
    ap.set_defaults(**{key:defaultValue})

def makeArgParser():
    ap = argparse.ArgumentParser(\
        formatter_class=lambda prog: argparse.HelpFormatter(prog,max_help_position=256))

    addFeatureOpt(ap, akEnableTemplateCollapsing, ckEnableTemplateCollapsing, True, \
        "template collapsing")

    addFeatureOpt(ap, akEnableNamespaceReplacements, ckEnableNamespaceReplacements, True, \
        "namespace replacements")

    addFeatureOpt(ap, akEnableGenericReplacements, ckEnableGenericReplacements, True, \
        "generic replacements")

    addFeatureOpt(ap, akEnableTempCache, ckEnableTempCache, True, \
        "temp cache")

    addFeatureOpt(ap, akReprocess, ckReprocess, False, \
        "Reprocess previous source")

    addFeatureOpt(ap, akReprocessPrevConfig, ckReprocessPrevConfig, True, \
        "Reprocess with previous configuration")

    ap.add_argument('-d', '--depth', \
        help="Template collapsing depth", \
        type=int, default=1, dest=ckTemplateCollapsingDepth, metavar='X')

    ap.add_argument('-c', '--config', \
        help="Configuration file path(s)", \
        type=str, default="", dest=ckConfigPaths, metavar='P')

    # TODO:
    #
    # ap.add_argument('-x', '--exec', \
    #     help="Execute compilation command", \
    #     type=str, default="", nargs=argparse.REMAINDER, dest=ckCompilationCommand, metavar='X')

    return ap

def propagateArgOverride(key, origin, target):
    if key in origin.keys():
        target[key] = origin[key]

def propagateReplacements(key, origin, target):
    if key in origin.keys():
        for k, v in origin[key].items():
            target[key][k] = v

def propagateConfigPaths(key, origin, target):
    if key in origin.keys():
        for x in origin[key]:
            target[key].add(x)

def propagateEverything(origin, target):
    propagateArgOverride(ckEnableNamespaceReplacements, origin, target)
    propagateArgOverride(ckEnableGenericReplacements, origin, target)
    propagateArgOverride(ckEnableTemplateCollapsing, origin, target)
    propagateArgOverride(ckEnableTempCache, origin, target)
    propagateArgOverride(ckTemplateCollapsingDepth, origin, target)

    propagateReplacements(ckNamespaceReplacements, origin, target)
    propagateReplacements(ckGenericReplacements, origin, target)

def loadConfig(path):
    with open(path) as data:
        j = json.load(data)
        res = {
            ckNamespaceReplacements: dict(),
            ckGenericReplacements: dict(),
            ckConfigPaths: set()
        }

        propagateEverything(j, res)
        propagateConfigPaths(ckConfigPaths, j, res)

        return res

# TODO:
class Camomilla:
    def __init__(self, conf):
        self._conf = conf

    def namespaceReplacements(self):
        return self._conf[ckNamespaceReplacements]

    def genericReplacements(self):
        return self._conf[ckGenericReplacements]

    def templateCollapsingDepth(self):
        return self._conf[ckTemplateCollapsingDepth]

    def enableNamespaceReplacements(self):
        return self._conf[ckEnableNamespaceReplacements]

    def enableGenericReplacements(self):
        return self._conf[ckEnableGenericReplacements]

    def enableTemplateCollapsing(self):
        return self._conf[ckEnableTemplateCollapsing]

    def enableTempCache(self):
        return self._conf[ckEnableTempCache]

    # Find all `<...>` pair ranges
    def _find_angles(self, s, xi_start, xi_end):
        result_angle_pairs = []
        open_angles = []

        for i in range(xi_start, xi_end):
            if s[i-1] != ' ' and s[i] == '<':
                open_angles.append(i)

            elif s[i-1] != '-' and s[i] == '>':
                if len(open_angles) == 0:
                    continue

                depth = len(open_angles)
                x = open_angles.pop()
                result_angle_pairs.append((x, i+1, depth))

        return result_angle_pairs

    # Mark a `<...>` pair for removal
    def _mark(self, i_start, i_end):
        return (i_start + 1, i_end - 1)

    # Yield merged overlapping intervals
    # (From 'http://codereview.stackexchange.com/questions/69242')
    def _merged(self, intervals):
        sorted_intervals = sorted(intervals, key=lambda x: x[0])

        if not sorted_intervals:  # no intervals to merge
            return

        # low and high represent the bounds of the current run of merges
        low, high = sorted_intervals[0]

        for iv in sorted_intervals[1:]:
            if iv[0] <= high:  # new interval overlaps current run
                high = max(high, iv[1])  # merge with the current run
            else:  # current run is over
                yield low, high  # yield accumulated interval
                low, high = iv  # start new run

        yield low, high  # end the final run

    # From http://stackoverflow.com/questions/15175142/
    def _multiple_replace(self, k_mapper, v_mapper, xdict, src):
        # Bail out if there are no replacements
        if len(xdict) == 0:
            return src

        # Map keys and values in dictionary
        mapped_dict = {k_mapper(k): v_mapper(v) for k, v in xdict.items()}

        # Create a regular expression  from the dictionary keys
        escaped_keys = map(re.escape, mapped_dict.keys())
        joined_regex_matcher = "({})".format("|".join(escaped_keys))
        regex = re.compile(joined_regex_matcher)

        # For each match, look-up corresponding value in dictionary
        return regex.sub(lambda x: mapped_dict[x.string[x.start():x.end()]], src)

    def process(self, src):
        out = ""
        marked = []

        # Write temp cache ______________________________________
        #
        if self.enableTempCache():
            # Cache source error
            writeTempCache(src)

            # Cache config
            writeTempConfigCache(json.dumps(self._conf))
        # _______________________________________________________
        #

        # Template collapsing ___________________________________
        #
        if self.enableTemplateCollapsing():
            # Find all angle bracket pairs
            angle_pairs = self._find_angles(src, 0, len(src))

            # Mark pairs matching desired depth for removal
            for p in angle_pairs:
                if p[2] > self.templateCollapsingDepth():
                    marked.append(self._mark(p[0], p[1]))

            # Build output string by avoiding marked intervals
            last = 0
            for m in self._merged(marked):
                out += src[last:m[0]]
                last = m[1]
            out += src[last:len(src)]
        # _______________________________________________________
        #

        # Namespace replacements_________________________________
        #
        if self.enableNamespaceReplacements():
            # Replace namespace matches
            out = self._multiple_replace( \
                lambda k: k + r'::', \
                lambda v: v + r'::' if len(v) > 0 else '', \
                self.namespaceReplacements(), out)
        # _______________________________________________________
        #

        # Generic replacements __________________________________
        #
        if self.enableGenericReplacements():
            # Replace generic matches
            out = self._multiple_replace( \
                lambda k: k, \
                lambda v: v, \
                self.genericReplacements(), out)
        # _______________________________________________________
        #

        return out

def mergeConfig(parent, x):
    # Recursively merge configs
    if ckConfigPaths in x.keys():
        for child in x[ckConfigPaths]:
            x = mergeConfig(x, loadConfig(child))

    propagateEverything(x, parent)
    return parent

def makeInitialConfig(args):
    conf = vars(args[0])
    conf[ckNamespaceReplacements] = dict()
    conf[ckGenericReplacements] = dict()
    conf[ckConfigPaths] = [] if len(conf[ckConfigPaths]) == 0 else conf[ckConfigPaths].split(' ')

    conf[ckNamespaceReplacements]["std"] = ""
    conf[ckGenericReplacements]["<>"] = "<?>"

    return conf

def makeFinalConfig():
    ap = makeArgParser()
    args = ap.parse_known_args()
    conf = makeInitialConfig(args)

    # TODO:
    #
    # compilationCmd = ' '.join(conf[ckCompilationCommand])
    #
    # if compilationCmd == "":
    #     src = sys.stdin.read()
    # else:
    #     print("Warning: stdin data will be ignored because '-x' is being used.")
    #     os.system('(' + compilationCmd + ')')

    for child in conf[ckConfigPaths]:
        conf = mergeConfig(conf, loadConfig(child))

    return conf



#
#
#
# -----------------------------------------------------------------------------------------------------------
# Main
# -----------------------------------------------------------------------------------------------------------

def main():
    conf = makeFinalConfig()
    camomilla = Camomilla(conf)

    # If reprocessing with previous config, load it and override with command line
    if conf[ckReprocess] and conf[ckReprocessPrevConfig]:
        ap = makeArgParser()
        args = ap.parse_known_args()
        conf = makeInitialConfig(args)
        conf = mergeConfig(conf, loadConfig(fkCacheConfigFilePath))
        conf = mergeConfig(conf, makeInitialConfig(args))

    # Read from temp cache if reprocessing, otherwise from stdin
    src = readTempCache() if conf[ckReprocess] else sys.stdin.read()

    # Print processed error
    print(camomilla.process(src))
    return 0

if __name__ == "__main__":
    sys.exit(main())
